@extends('layouts.web-layout')

@section('addStyle')
@endsection

@section('contents')
    @include('layouts.include.sub-menu-wrap')

    <article class="sub-contents">
        <div class="sub-conbox inner-layer">
            <div class="table-wrap">
                <table class="cst-table">
                    <caption class="hide">평의원</caption>
                    <colgroup>
                        <col style="width: 35%">
                        <col>
                        <col>
                    </colgroup>
                    <thead>
                        <tr class="active">
                            <th scope="col">성명</th>
                            <th scope="col">소속</th>
                            <th scope="col">전공과목</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr> 
                            <td>강혜련</td>
                            <td>서울의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>고영일</td>
                            <td>전남의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>권순석</td>
                            <td>가톨릭의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김규언</td>
                            <td>소화아동병원</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                        
                            <td>김규한</td>
                            <td>서울의대</td>
							<td>피부과</td>
                        </tr>
                        <tr>
                            <td>김동영</td>
                            <td>서울의대</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>김미경</td>
                            <td>충북의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김봉성</td>
                            <td>강릉아산병원</td>
							<td>소아청소년과</td>
                        </tr>

                        <tr>
                            <td>김상헌</td>
                            <td>한양의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김상훈</td>
                            <td>을지의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김선태</td>
                            <td>가천의대</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>김성완</td>
                            <td>경희의대</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>김유영</td>
                            <td>서울의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김정희</td>
                            <td>인하의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>김철우</td>
                            <td>인하의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김태범</td>
                            <td>울산의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>김현희</td>
                            <td>가톨릭의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>나영호</td>
                            <td>성북 우리아이들병원</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>남동호</td>
                            <td>아주의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>동헌종</td>
                            <td>하나이비인후과병원</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>문희범</td>
                            <td>울산의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>민양기</td>
                            <td>경찰병원</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>박성학</td>
                            <td>가톨릭의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>박용민</td>
                            <td>건국의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>박중원</td>
                            <td>연세의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>박춘식</td>
                            <td>순천향의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>박해심</td>
                            <td>아주의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>박흥우</td>
                            <td>서울의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>손명현</td>
                            <td>연세의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>신동학</td>
                            <td>계명의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>심정연</td>
                            <td>성균관의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>안강모</td>
                            <td>성균관의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>양현종</td>
                            <td>순천향의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>염혜영</td>
                            <td>서울의료원</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>오무영</td>
                            <td>온종합병원</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>오재원</td>
                            <td>한양의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>유광하</td>
                            <td>건국의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>유영</td>
                            <td>고려의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>유진호</td>
                            <td>울산의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>윤혜선</td>
                            <td>한림의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>윤호주</td>
                            <td>한양의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이병재</td>
                            <td>성균관의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이상표</td>
                            <td>가천의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이수영</td>
                            <td>아주의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>이숙영</td>
                            <td>가톨릭의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이애영</td>
                            <td>동국의대</td>
							<td>피부과</td>
                        </tr>
                        <tr>
                            <td>이영목</td>
                            <td>GF내과</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이용철</td>
                            <td>전북의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이재서</td>
                            <td>서울의대</td>
							<td>이비인후과</td>
                        </tr>
                        <tr>
                            <td>이종명</td>
                            <td>경북의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>이준혁</td>
                            <td>순천향의대</td>
							<td>내과</td>
                        </tr>

                        <tr>
                            <td>이하백</td>
                            <td>한양의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>이혜란</td>
                            <td>한림의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>임대현</td>
                            <td>인하의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>장광천</td>
                            <td>국민건강보험 일산병원</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>장석일</td>
                            <td>성애병원</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>장안수</td>
                            <td>순천향의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>장윤석</td>
                            <td>서울의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>정이영</td>
                            <td>경상의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>정재원</td>
                            <td>인제의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>조상헌</td>
                            <td>서울의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>조영주</td>
                            <td>이화의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>조유숙</td>
                            <td>울산의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>지영구</td>
                            <td>단국의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>최동철</td>
                            <td>성균관의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>최병휘</td>
                            <td>중앙의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>최정희</td>
                            <td>한림의대</td>
							<td>내과</td>
                        </tr>
                        <tr>
                            <td>편복양</td>
                            <td>순천향의대 </td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>한만용</td>
                            <td>차의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>홍수종</td>
                            <td>울산의대</td>
							<td>소아청소년과</td>
                        </tr>
                        <tr>
                            <td>홍천수</td>
                            <td>연세의대</td>
							<td>내과</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </article>

@endsection

@section('addScript')
@endsection
