<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
<meta name="format-detection" content="telephone=no, address=no, email=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="Author" content="대한천식알레르기학회">
<meta name="Keywords" content="대한천식알레르기학회">
<meta name="description" content="대한천식알레르기학회">
<title>대한천식알레르기학회</title>
<link rel="icon" href="/assets/image/favicon.ico">
<link type="text/css" rel="stylesheet" href="/assets/css/slick.css">
<link type="text/css" rel="stylesheet" href="/assets/css/jquery-ui.min.css">
<link type="text/css" rel="stylesheet" href="/assets/css/common.css">
<script type="text/javascript" src="/assets/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/assets/js/slick.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery.rwdImageMaps.js"></script>
<script type="text/javascript" src="/assets/js/common.js"></script>
</head>

<body>
    <!-- 
        main일 때 calss="main"
        sub일 때 class="sub"
    -->
    <div class="wrap <?php echo $main;?>">
        <header id="header" class="js-header">
            <div class="header-wrap inner-layer">
                <ul class="sns-menu">
                    <li><a href="https://www.instagram.com/allergy_kaaaci/" target="_blank"><img src="/assets/image/common/ic_insta.png" alt="인스타그램"></a></li>
                    <li><a href="#n"><img src="/assets/image/common/ic_facebook.png" alt="페이스북"></a></li>
                    <li><a href="https://www.youtube.com/@Kaaaci_Allergy" target="_blank"><img src="/assets/image/common/ic_youtube.png" alt="유튜브"></a></li>
                </ul>
                <h1 class="header-logo">
                    <a href="/"><img src="/assets/image/common/h1_logo.png" alt="대한천식알레르기학회. The Korean Academy of Asthma, Allergy and Clinical Immunology"></a>
                </h1>
                <ul class="util-menu">
                    <li class="admin"><a href="#n">ADMIN</a></li>
                    <li class="home"><a href="/">HOME</a></li>
                    <li class="signup"><a href="#n">마이페이지</a></li>
                    <li class="login"><a href="#n">LOGOUT</a></li>
                    <li class="lang"><a href="https://www.allergy.or.kr/eng/" target="_blank">ENGLISH</a></li>
                </ul>
                <button type="button" class="btn btn-menu-open js-btn-menu-open" title="메뉴 열기">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>

            <div id="dim" class="js-dim"></div>
            <nav id="gnb">
                <div class="m-gnb-header">
                    <ul class="util-menu">
                        <li class="login"><a href="#n">LOGIN</a></li>
                        <li class="signup"><a href="#n">회원가입 안내</a></li>
                        <li class="admin"><a href="#n">ADMIN</a></li>
                    </ul>
                </div>
                <div class="gnb-wrap inner-layer">
                    <ul class="gnb js-gnb">
                        <li>
                            <a href="#n"><span>학회소개</span></a>
                            <ul>
                                <li><a href="#n">인사말</a></li>
                                <li><a href="#n">연혁</a></li>
                                <li><a href="#n">회칙</a></li>
                                <li><a href="#n">조직</a></li>
                                <li><a href="#n">오시는길</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>학술지</span></a>
                            <ul>
                                <li><a href="#n">AARD 투고규정</a></li>
                                <li><a href="#n">AARD 논문검색</a></li>
                                <li><a href="#n">AAIR 투고규정</a></li>
                                <li><a href="#n">천식 및 알레르기</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>학술행사</span></a>
                            <ul>
                                <li><a href="#n">행사일정</a></li>
                                <li><a href="#n">역대학술대회</a></li>
                                <li><a href="#n">해외학회일정</a></li>
                                <li><a href="#n">국내학술대회</a></li>
                                <li><a href="#n">교육강좌</a></li>
                                <li><a href="#n">포토갤러리</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>게시판</span></a>
                            <ul>
                                <li><a href="#n">공지사항</a></li>
                                <li><a href="#n">연구팀 게시판</a></li>
                                <li><a href="#n">지회 게시판</a></li>
                                <li><a href="#n">서식</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>일반인 정보</span></a>
                            <ul>
                                <li><a href="#n">아토피 천식 교육 정보센터</a></li>
                                <li><a href="#n">알레르기 전문병원 검색</a></li>
                                <li><a href="#n">알레르기 정보</a></li>
                                <li><a href="#n">대한천식알레르기학회 리포트</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>Membership</span></a>
                            <ul>
                                <li><a href="#n">로그인</a></li>
                                <li><a href="#n">아이디 / 비밀번호 찾기</a></li>
                                <li><a href="#n">회원가입 안내</a></li>
                                <li><a href="#n">개인정보취급방침</a></li>
                                <li><a href="#n">이메일 수집 거부</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>My Page</span></a>
                            <ul>
                                <li><a href="#n">개인정보 수정</a></li>
                                <li><a href="#n">회비납부현황조회</a></li>
                                <li><a href="#n">학술대회 참석현황</a></li>
                                <li><a href="#n">회원탈퇴</a></li>
                                <li><a href="#n">책갈피</a></li>
                            </ul>
                        </li>
                    </ul>
                    <button type="button" class="btn btn-allmenu js-allmenu-open" title="전체메뉴">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                </div>
                <ul class="sns-menu">
                    <li class="lang"><a href="#n">ENGLISH</a></li>
                    <li><a href="#n"><img src="/assets/image/common/ic_insta.png" alt="인스타그램"></a></li>
                    <li><a href="#n"><img src="/assets/image/common/ic_facebook.png" alt="페이스북"></a></li>
                    <li><a href="#n"><img src="/assets/image/common/ic_youtube.png" alt="유튜브"></a></li>
                </ul>
                <button type="button" class="btn btn-menu-close js-btn-menu-close"><span class="hide">메뉴 닫기</span></button>
            </nav>
        </header>

        <article id="allmenu" class="js-allmenu">
            <div class="allmenu-wrap inner-layer">
                <h3 class="tit">전체 메뉴</h3>
                <ul>
                    <li>
                        <a href="#n"><span>학회소개</span></a>
                        <ul>
                            <li><a href="#n">인사말</a></li>
                            <li><a href="#n">연혁</a></li>
                            <li><a href="#n">회칙</a></li>
                            <li><a href="#n">조직</a></li>
                            <li><a href="#n">오시는길</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>학술지</span></a>
                        <ul>
                            <li><a href="#n">AARD 투고규정</a></li>
                            <li><a href="#n">AARD 논문검색</a></li>
                            <li><a href="#n">AAIR 투고규정</a></li>
                            <li><a href="#n">천식 및 알레르기</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>학술행사</span></a>
                        <ul>
                            <li><a href="#n">행사일정</a></li>
                            <li><a href="#n">역대학술대회</a></li>
                            <li><a href="#n">해외학회일정</a></li>
                            <li><a href="#n">국내학술대회</a></li>
                            <li><a href="#n">교육강좌</a></li>
                            <li><a href="#n">포토갤러리</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>게시판</span></a>
                        <ul>
                            <li><a href="#n">공지사항</a></li>
                            <li><a href="#n">연구팀 게시판</a></li>
                            <li><a href="#n">지회 게시판</a></li>
                            <li><a href="#n">서식</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>일반인 정보</span></a>
                        <ul>
                            <li><a href="#n">아토피 천식 교육 정보센터</a></li>
                            <li><a href="#n">알레르기 전문병원 검색</a></li>
                            <li><a href="#n">알레르기 정보</a></li>
                            <li><a href="#n">대한천식알레르기학회 리포트</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>Membership</span></a>
                        <ul>
                            <li><a href="#n">로그인</a></li>
                            <li><a href="#n">아이디 / 비밀번호 찾기</a></li>
                            <li><a href="#n">회원가입 안내</a></li>
                            <li><a href="#n">개인정보취급방침</a></li>
                            <li><a href="#n">이메일 수집 거부</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n"><span>My Page</span></a>
                        <ul>
                            <li><a href="#n">개인정보 수정</a></li>
                            <li><a href="#n">회비납부현황조회</a></li>
                            <li><a href="#n">학술대회 참석현황</a></li>
                            <li><a href="#n">회원탈퇴</a></li>
                            <li><a href="#n">책갈피</a></li>
                        </ul>
                    </li>
                </ul>
                <button type="button" class="btn btn-allmenu-close js-allmenu-close"><span class="hide">메뉴 닫기</span></button>
            </div>
        </article>