<?php

return [
    // ================= web menu =================
    'main' => [
        'M1' => [
            'name' => '학회소개',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M2' => [
            'name' => '학회소식',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M3' => [
            'name' => '자료실',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M4' => [
            'name' => '학술지 및 간행',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M5' => [
            'name' => '학술행사',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M6' => [
            'name' => '진료지침',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => true,
        ],
        'M7' => [
            'name' => '일반인정보',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],

        'MYPAGE' => [
            'name' => 'Membership / My Page',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
    ],

    'sub' => [
        'M1' => [ // 학회소개
            'S1' => [
                'name' => '인사말',
                'route' => 'intro.greeting',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '학회 역사 & 연혁',
                'route' => 'intro.history',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '미션 & 비전',
                'route' => 'intro.mission',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '회칙',
                'route' => 'intro.regulation',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '임원',
                'route' => 'intro.executive',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '위원회',
                'route' => 'intro.committee',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S7' => [
                'name' => '평의원',
                'route' => 'intro.councilor',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S8' => [
                'name' => '지회',
                'route' => 'intro.branch',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S9' => [
                'name' => '연구팀',
                'route' => 'intro.research',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S10' => [
                'name' => '오시는길',
                'route' => 'intro.direction',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M2' => [ // 학회소식
            'S1' => [
                'name' => '공지사항',
                'route' => 'board',
                'param' => ['code'=>'notice'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '시상내역',
                'route' => 'news.prize',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '분과전문의 자격시험',
                'route' => 'news.cpa',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M3' => [ // 자료실
            'S1' => [
                'name' => '천식 E-러닝',
                'route' => 'archive.eLearning',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '자료실',
                'route' => 'board',
                'param' => ['code'=>'archive'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '서식',
                'route' => 'board',
                'param' => ['code'=>'format'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M4' => [ // 학술지 및 간행 JOURNAL
            'S1' => [
                'name' => '뉴스레터',
                'route' => 'board',
                'param' => ['code'=>'newsletter'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '최신논문소식',
                'route' => 'board',
                'param' => ['code'=>'abs-news'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '교과서 안내',
                'route' => 'journal.publication',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => 'AARD소개',
                'route' => 'journal.aard',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => 'AAIR소개',
                'route' => 'journal.aair',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '천식 및 알레르기',
                'route' => 'journal.asSearch',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M5' => [ // 학술행사
            'S1' => [
                'name' => '행사일정',
                'route' => 'board',
                'param' => ['code'=>'event-schedule'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '국외학술대회참가신청',
                'route' => 'workshop.overseas',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '국내학술대회',
                'route' => 'board',
                'param' => ['code'=>'domestic'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '교육강좌',
                'route' => 'workshop.domestic',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '역대학술대회',
                'route' => 'board',
                'param' => ['code'=>'past-workshop'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '포토갤러리',
                'route' => 'board',
                'param' => ['code'=>'photo'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],

        ],
        'M6' => [ // 진료지침
            'S1' => [
                'name' => '진료지침',
                'route' => 'board',
                'param' => ['code'=>'treatment','gubun'=>'1'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '개발 중 진료지침',
                'route' => 'board',
                'param' => ['code'=>'treatment','gubun'=>'2'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '진료지침 게시판',
                'route' => 'board',
                'param' => ['code'=>'guideline'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],

        ],
        'M7' => [ // 일반인 정보
            'S1' => [
                'name' => '아토피 천식 교육 정보센터',
                'route' => 'general.center',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '알레르기 전문병원 검색',
                'route' => 'general.hospitalSearch',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '알레르기 정보',
                'route' => 'board',
                'param' => ['code'=>'allergy-info'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '대한천식알레르기학회 리포트',
                'route' => 'board',
                'param' => ['code'=>'report'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],

        'MYPAGE' => [ // 마이페이지
            'S1' => [
                'name' => '로그인',
                'route' => 'login',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '아이디 / 비밀번호 찾기',
                'route' => 'findId',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '회원가입 안내',
                'route' => 'join',
                'param' => ['step'=>'1'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '개인정보취급방침',
                'route' => 'privacy',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
//            'S5' => [
//                'name' => '이메일 수집 거부',
//                'route' => null,
//                'param' => [],
//                'url' => "javascript:BsJsOpenLayer('#pop-email');",
//                'continue' => false,
//                'blank'=>false,
//                'isLogined' => false,
//            ],

            'S6' => [
                'name' => 'Intro',
                'route' => 'mypage.intro',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S7' => [
                'name' => '개인정보 수정',
                'route' => 'mypage.pwCheck',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S8' => [
                'name' => '비밀번호 변경',
                'route' => 'mypage.password',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S9' => [
                'name' => '회비납부 현황 조회',
                'route' => 'mypage.fee',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S10' => [
                'name' => '학술대회 참석현황',
                'route' => 'mypage.certi',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S11' => [
                'name' => '회원검색',
                'route' => 'mypage.member_search',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S12' => [
                'name' => '책갈피',
                'route' => 'mypage.bookmark',
                'param' => ['code'=>'event-schedule'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],
            'S13' => [
                'name' => '회원탈퇴',
                'route' => 'mypage.withdraw',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => true,
            ],

        ],
    ],
];
