<?php

return [
    // ================= web menu =================
    'main' => [
        'M1' => [
            'name' => '학회소개',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M2' => [
            'name' => '학술지',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M3' => [
            'name' => '학술행사',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M4' => [
            'name' => '회원공간',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => true,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M5' => [
            'name' => '진료지침',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => true,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M6' => [
            'name' => '게시판',
            'route' => 'board',
            'param' => ['code'=>'notice'],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M7' => [
            'name' => '일반인정보',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M8' => [
            'name' => 'Membership',
            'route' => '',
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'MYPAGE' => [
            'name' => 'MYPAGE',
            'route' => 'mypage.intro',
            'param' => [],
            'url' => '',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
    ],

    'sub' => [
        'M1' => [ // 학회소개
            'S1' => [
                'name' => '인사말',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '연혁',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '회칙',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '조직',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '오시는길',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M2' => [ // 학술지
            'S1' => [
                'name' => 'AARD 투고규정',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => 'AARD 논문검색',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => 'AAIR 투고규정',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '천식 및 알레르기',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M3' => [ // 학술행사
            'S1' => [
                'name' => '행사일정',
                'route' => 'board',
                'param' => ['code'=>'event-schedule'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '역대학술대회',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '해외학회일정',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '국내학술대회',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '교육강좌',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '포토갤러리',
                'route' => 'board',
                'param' => ['code'=>'photo'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M4' => [ // 회원공간
            'S1' => [
                'name' => '천식 E-러닝',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '뉴스레터',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '자료실',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '회원검색',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '분과전문의자격시험',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '최신논문소식',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M5' => [ // 진료지침
            'S1' => [
                'name' => '진료지침',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '개발 중 진료지침',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '진료지침 게시판',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M6' => [ // 게시판
            'S1' => [
                'name' => '공지사항',
                'route' => 'board',
                'param' => ['code'=>'notice'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '연구팀 게시판',
                'route' => 'board',
                'param' => ['code'=>'research-team'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '지회 게시판',
                'route' => 'board',
                'param' => ['code'=>'branch'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '서식',
                'route' => 'board',
                'param' => ['code'=>'format'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M7' => [ // 일반인 정보
            'S1' => [
                'name' => '아토피 천식 교육 정보센터',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '알레르기 전문병원 검색',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '알레르기 정보',
                'route' => 'board',
                'param' => ['code'=>'allergy-info'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '대한천식알레르기학회 리포트',
                'route' => 'board',
                'param' => ['code'=>'report'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M8' => [ // Membership
            'S1' => [
                'name' => '로그인',
                'route' => 'login',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '아이디 / 비밀번호 찾기',
                'route' => 'findId',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '회원가입 안내',
                'route' => 'join',
                'param' => ['step'=>'1'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '개인정보취급방침',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '이메일 수집 거부',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'MYPAGE' => [ // 마이페이지
            'S1' => [
                'name' => '개인정보 수정',
                'route' => 'mypage.pwCheck',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => '비밀번호 변경',
                'route' => 'mypage.password',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => '회비납부 현황 조회',
                'route' => 'mypage.fee',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S4' => [
                'name' => '학술대회 참석현황',
                'route' => 'mypage.certi',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S5' => [
                'name' => '책갈피',
                'route' => 'mypage.bookmark',
                'param' => ['code'=>'event-schedule'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S6' => [
                'name' => '회원탈퇴',
                'route' => 'mypage.withdraw',
                'param' => [],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S9' => [
                'name' => 'Intro',
                'route' => null,
                'param' => [],
                'url' => 'javascript',
                'continue' => true,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
    ],
];
