<?php

return [
    // ================= web menu =================
    'main' => [
        'M1' => [
            'name' => 'About KAAACI',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M2' => [
            'name' => 'ORGANIZATION',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M3' => [
            'name' => 'PUBLICATION',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M4' => [
            'name' => 'ACADEMIC MEETINGS',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M5' => [
            'name' => 'NEWS & NOTICE',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => false,
        ],
        'M6' => [
            'name' => 'PHOTOGRAPH',
            'route' => null,
            'param' => [],
            'url' => 'javascript:;',
            'dev' => false,
            'continue' => false,
            'blank'=>false,
            'isLogined' => true,
        ],

    ],

    'sub' => [
        'M1' => [
            'S1' => [
                'name' => 'Welcome Message',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => 'History',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => 'Contact Us',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M2' => [
            'S1' => [
                'name' => 'Committee',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => 'Regional Branches',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => 'Working Group',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M3' => [
            'S1' => [
                'name' => 'AAIR',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S2' => [
                'name' => 'AARD',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
            'S3' => [
                'name' => 'Textbook',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M4' => [
            'S1' => [
                'name' => 'Meetings',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M5' => [
            'S1' => [
                'name' => 'NEWS & NOTICE',
                'route' => 'board',
                'param' => ['code'=>'news'],
                'url' => null,
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],
        'M6' => [
            'S1' => [
                'name' => 'PHOTOGRAPH',
                'route' => null,
                'param' => [],
                'url' => 'javascript:;',
                'continue' => false,
                'blank'=>false,
                'isLogined' => false,
            ],
        ],

    ],
];
