
        <!-- footer -->
        <footer id="footer">
            <div class="footer-wrap inner-layer">
                <p>Copyright (c) 2014 THE KOREAN ACADEMY OF ASTHMA, ALLERGY AND CLINICAL IMMUNOLOGY. All Rights Reserved.</p>
                <button type="button" class="btn-top js-btn-top">
                    <img src="/html/english/assets/image/common/img_top.png" alt="">
                </button>
            </div>
        </footer>
        <!-- //footer -->
    </div>
</body>
</html>