<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="Author" content="대한천식알레르기학회 영문">
    <meta name="Keywords" content="대한천식알레르기학회 영문">
    <meta name="description" content="대한천식알레르기학회 영문">
    <title>대한천식알레르기학회 영문</title>
    <link rel="icon" href="/assets/image/favicon.ico">
    <link type="text/css" rel="stylesheet" href="/html/english/assets/css/slick.css">
    <link type="text/css" rel="stylesheet" href="/html/english/assets/css/common.css">
    <link type="text/css" rel="stylesheet" href="/html/english/assets/css/jquery-ui.min.css">
    <script type="text/javascript" src="/html/english/assets/js/jquery-3.7.1.min.js"></script>
    <script type="text/javascript" src="/html/english/assets/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/html/english/assets/js/slick.min.js"></script>
    <script type="text/javascript" src="/html/english/assets/js/jquery.rwdImageMaps.js"></script>
    <script type="text/javascript" src="/html/english/assets/js/common.js"></script>
</head>
<body>
    <!-- 
        main일 때 calss="main"
        sub일 때 class="sub"
    -->
    <div class="wrap sub">
        <!-- header -->
        <header id="header" class="js-header">
            <div class="header-wrap inner-layer">
                <h1 class="header-logo">
                    <a href="#n">헤더 로고</a>
                </h1>
                <ul class="util-menu">
                    <li><a href="#n">KOREAN</a></li>
                    <li><a href="#n" class="btn-allmenu js-allmenu-open">SITEMAP</a></li>
                    <li><a href="https://www.instagram.com/allergy_kaaaci/" target="_blank"><img src="/html/english/assets/image/common/img_instagram.png" alt="instagram"></a></li>
                    <li><a href="https://www.youtube.com/@Kaaaci_Allergy" target="_blank"><img src="/html/english/assets/image/common/img_youtube.png" alt="youtube"></a></li>
                </ul>
                <button type="button" class="btn btn-menu-open js-btn-menu-open"><span class="hide">메뉴 열기</span></button>
            </div>
            <div id="dim" class="js-dim"></div>
            <nav id="gnb">
                <div class="m-gnb-header">
                    <ul class="util-menu">
                        <li><a href="https://www.instagram.com/allergy_kaaaci/" target="_blank"><img src="/html/english/assets/image/common/img_instagram.png" alt="instagram"></a></li>
                        <li><a href="https://www.youtube.com/@Kaaaci_Allergy" target="_blank"><img src="/html/english/assets/image/common/img_youtube.png" alt="youtube"></a></li>
                    </ul>
                    <button type="button" class="btn btn-menu-close js-btn-menu-close"><span class="hide">메뉴 닫기</span></button>
                </div>
                <div class="gnb-wrap inner-layer">
                    <ul class="gnb js-gnb">
                        <li>
                            <a href="#n">About KAAACI</a>
                            <ul>
                                <li><a href="#n">Welcome Message</a></li>
                                <li><a href="#n">History</a></li>
                                <li><a href="#n">Contact Us</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">ORGANIZATION</a>
                            <ul>
                                <li><a href="#n">Committee	</a></li>
                                <li><a href="#n">Regional Branches</a></li>
                                <li><a href="#n">Working Group</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">PUBLICATION</a>
                            <ul>
                                <li><a href="#n">AAIR</a></li>
                                <li><a href="#n">AARD</a></li>
                                <li><a href="#n">Textbook</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">ACADEMIC MEETINGS</a>
                            <ul>
                                <li><a href="#n">Meetings</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">NEWS & NOTICE</a>
                            <ul>
                                <li><a href="#n">NEWS & NOTICE</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">PHOTOGRAPH</a>
                            <ul>
                                <li><a href="#n">PHOTOGRAPH</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        
        <section id="allmenu" class="js-allmenu">
            <div class="allmenu-wrap inner-layer">
                <h3 class="tit">SITEMAP</h3>
                <ul>
                    <li>
                        <a href="#n">About KAAACI</a>
                        <ul>
                            <li><a href="#n">Welcome Message</a></li>
                            <li><a href="#n">History</a></li>
                            <li><a href="#n">Contact Us</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n">ORGANIZATION</a>
                        <ul>
                            <li><a href="#n">Committee	</a></li>
                            <li><a href="#n">Regional Branches</a></li>
                            <li><a href="#n">Working Group</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n">PUBLICATION</a>
                        <ul>
                            <li><a href="#n">AAIR</a></li>
                            <li><a href="#n">AARD</a></li>
                            <li><a href="#n">Textbook</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n">ACADEMIC MEETINGS</a>
                        <ul>
                            <li><a href="#n">Meetings</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n">NEWS & NOTICE</a>
                        <ul>
                            <li><a href="#n">NEWS & NOTICE</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#n">PHOTOGRAPH</a>
                        <ul>
                            <li><a href="#n">PHOTOGRAPH</a></li>
                        </ul>
                    </li>
                </ul>
                <button type="button" class="btn btn-allmenu-close js-allmenu-close"><span class="hide">메뉴 닫기</span></button>
            </div>
        </section>
        <!-- //header -->